apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-pg
  namespace: postgresql
spec:
  instances: 3
  storage:
    size: 30Gi
  bootstrap:
    initdb:
      database: sentry
      owner: sentry
      secret:
        name: sentry-user-secret
  users:
    - name: sentry
      secret:
        name: sentry-user-secret
  postgresql:
    parameters:
      shared_preload_libraries: 'pg_stat_statements'
      pg_stat_statements.track: 'all'
---
apiVersion: v1
kind: Secret
metadata:
  name: sentry-user-secret
type: Opaque
data:
  password: c2VudHktcG9zdGdyZXMtcGFzc3dvcmQ=  # Закодированный пароль "sentry-postgresql-password" в base64
