apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-pg
  namespace: postgresql
spec:
  instances: 3
  storage:
    size: 30Gi
  superuserSecret:
    name: sentry-user-secret
  bootstrap:
    initdb:
      database: sentry
      owner: sentry
      secret:
        name: sentry-user-secret
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
---
apiVersion: v1
kind: Secret
metadata:
  name: sentry-user-secret
  namespace: postgresql
type: Opaque
data:
  password: c2VudHktcG9zdGdyZXMtcGFzc3dvcmQ=  # Закодированный пароль "sentry-postgresql-password" в base64
